package exposed.chapter_5

import exposed.AbstractPostgreSqlTest
import exposed.withTransaction
import kotlin.test.Test
import kotlin.test.assertFails

// https://www.postgresql.org/docs/18/ddl-identity-columns.html
class chapter5_3 : AbstractPostgreSqlTest() {
    // An identity column is a special column that is generated automatically from an implicit sequence.
    @Test
    fun `Identity Columns DEFAULT`() =
        withTransaction {
            exec(
                """
                CREATE TABLE people (
                    id bigint GENERATED BY DEFAULT AS IDENTITY
                );
                INSERT INTO people  DEFAULT VALUES;
                INSERT INTO people  DEFAULT VALUES;
                INSERT INTO people  DEFAULT VALUES;
                INSERT INTO people  DEFAULT VALUES;
                """.trimIndent(),
            )
            exec(
                """
                SELECT * FROM people;
                """.trimIndent(),
            ) {
                while (it.next()) {
                    it.getString(it.findColumn("id")).also { println("JQN $it") }
                }
            }
        }

    @Test
    fun `insert Identity Columns marked ALWAYS will be failed`() =
        withTransaction {
            assertFails {
                exec(
                    """
                    CREATE TABLE people (
                        id bigint GENERATED ALWAYS AS IDENTITY
                    );
                    INSERT INTO people (id) VALUES (12)
                    """.trimIndent(),
                )
            }
        }
}
