package chapter_5

import AbstractPostgreSqlTest
import org.jetbrains.exposed.v1.core.Table
import org.jetbrains.exposed.v1.javatime.CurrentTimestamp
import org.jetbrains.exposed.v1.javatime.datetime
import org.jetbrains.exposed.v1.javatime.timestamp
import org.jetbrains.exposed.v1.jdbc.SchemaUtils
import org.jetbrains.exposed.v1.jdbc.insert
import org.jetbrains.exposed.v1.jdbc.select
import org.jetbrains.exposed.v1.jdbc.selectAll
import withTransaction
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFails

// https://www.postgresql.org/docs/18/ddl-identity-columns.html
class chapter5_3 : AbstractPostgreSqlTest() {
    // An identity column is a special column that is generated automatically from an implicit sequence.
    @Test
    fun `Identity Columns DEFAULT`() =
        withTransaction {
            exec(
                """
                CREATE TABLE people (
                    id bigint GENERATED BY DEFAULT AS IDENTITY
                );
                INSERT INTO people  DEFAULT VALUES;
                INSERT INTO people  DEFAULT VALUES;
                INSERT INTO people  DEFAULT VALUES;
                INSERT INTO people  DEFAULT VALUES;
                """.trimIndent(),
            )
            exec(
                """
                SELECT * FROM people;
                """.trimIndent(),
            ) {
                while (it.next()) {
                    it.getString(it.findColumn("id")).also { println("JQN $it") }
                }
            }
        }

    @Test
    fun `insert Identity Columns marked ALWAYS will be failed`() =
        withTransaction {
            assertFails {
                exec(
                    """
                    CREATE TABLE people (
                        id bigint GENERATED ALWAYS AS IDENTITY
                    );
                    INSERT INTO people (id) VALUES (12)
                    """.trimIndent(),
                )
            }
        }
}
